target 'glife'

platform :ios

pod 'React', :path => '../node_modules/react-native'
pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'
pod 'react-native-background-service', :path => '../node_modules/react-native-background-service'