target 'Glimpse'

platform :ios, 9.0

pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'RCTImage'
]
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'RNSVG', :path => '../node_modules/react-native-svg'

rn_path = '../node_modules/react-native'
pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
pod 'GoogleSignIn', '~> 4.4.0'

# Add new pods below this line

pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

pod 'RealmSwift', '~> 3.17', :modular_headers => true

pod 'Realm', :modular_headers => true

pod 'FBSDKLoginKit'
