target 'Glimpse'

platform :ios, 9.0

pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'RCTImage'
]
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

rn_path = '../node_modules/react-native'
pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

pod 'GoogleSignIn'

# Add new pods below this line

pod 'RealmSwift'
pod 'Realm', :modular_headers => true